### ISSUE TITLE
What is the correct path of "renderer/public"?

### ISSUE THREAD

**Issue by immafrady** [Deluze/electron-vue-template#23] opened 2022-09-19 03:53 UTC
so i'm adding an 404.png in renderer/public,
and using it like `src="/404.png"`

it worked at develop mode, but failed to load at prod mode.

![image](https://user-images.githubusercontent.com/11257214/190946797-ffe02bf3-20ca-4798-b274-ec4deba9cf24.png)

it seems like after build at prod mode, the resource path become strange
![image](https://user-images.githubusercontent.com/11257214/190946989-f9c44a77-1a7d-4915-a15b-b6be74903469.png)

**Comment by Deluze** [comment] 2022-09-19 10:35
Seems like you don't have a `public` directory in your renderer.

You are missing your `public` directory in the renderer. Looking at `vite.config.js` you can see that `publicDir` is set to `public` by default. Moving `renderer/404.png` to `renderer/public/404.png` should fix your issue.

The path looks like a normal built electron application 😄 what do you think is strange?

**Comment by Deluze** [comment] 2022-09-19 11:10
Interesting, looking at your build directory it should find the 404.png on `/404.png`. What is being logged to the console? Are you getting a 404 from the network?

**Comment by Deluze** [comment] 2022-09-19 11:13
I tried this on my Windows & Mac system to be sure, but can't seem to reproduce.

**Comment by immafrady** [comment] 2022-09-30 08:44
I'm sorry for being busy and then forgot to reply.🥵

I've cloned a new project and try to reproduce the problem, and it seems ok.

I need to find the difference between your project and mine.

Thanks anyway😌

**Comment by dss886** [comment] 2024-01-23 06:33
@Deluze hi, I got the same problem.

I have a `google.png` image in the `src/renderer/public/` dir, and using it like `/google.png` in my vue file.

Everything works fine when in develop mode, but got an error when build to zip on Windows.

![image](https://github.com/Deluze/electron-vue-template/assets/5170950/4a87bef8-9ed9-4b04-90ae-c1f0dfad8a40)

The `/google.png` seems to be directed to the root directory like `file:///D:/google.png` (while my program is unpacked to the `D:/Software/xxx`).

Any help would be greatly appreciated!

**Comment by Deluze** [comment] 2024-01-23 07:17
Hey @dss886, what's your Vite config like? The default svg icons that come with this project work fine on my end.

**Comment by dss886** [comment] 2024-01-23 08:37
`vite.config.js`:

```javascript
const Path = require("path");
const vuePlugin = require("@vitejs/plugin-vue");

const { defineConfig } = require("vite");

/**
 * https://vitejs.dev/config
 */
const config = defineConfig({
    root: Path.join(__dirname, "src", "renderer"),
    publicDir: "public",
    server: {
        port: 8080,
    },
    open: false,
    build: {
        outDir: Path.join(__dirname, "build", "renderer"),
        emptyOutDir: true,
        rollupOptions: {
            input: {
                main: Path.join(__dirname, "src", "renderer", "index.html"),
                hardware: Path.join(__dirname, "src", "renderer", "plugins", "hardware", "index.html"),
                spotlight: Path.join(__dirname, "src", "renderer", "plugins", "spotlight", "index.html"),
            }
        }
    },
    plugins: [vuePlugin()],
});

module.exports = config;
```

Build Command: `node scripts/build.js && electron-builder --win zip:x64`

Build result is a zip file. After unzip is like:

![20240123163450](https://github.com/Deluze/electron-vue-template/assets/5170950/d7373fb0-c9cb-4c37-9f37-c175871d00c6)

Unzip the app.asar file:

![image](https://github.com/Deluze/electron-vue-template/assets/5170950/c92798d6-c517-4e95-a4be-899474bf2acd)

**Comment by Deluze** [comment] 2024-01-23 12:09
@dss886 The directory tree in your last screenshot looks correct. Vite's behavior is to pull any file from the public dir into the build root.

I tried to reproduce it on my Linux environment by packing up the build in a tar, deb and snap package but can't seem to reproduce.

Could you create a minimal repo to reproduce this issue? @dss886 
I'll try it on my Windows environment at a later time.

**Comment by Deluze** [comment] 2024-01-26 09:44
Thanks @dss886 I'll take a look this weekend

**Comment by tob-at-lovelace** [comment] 2024-02-20 22:18
Hi all. Maybe this is unrelated, but I was hitting this exact problem with code that I was porting over.

I'm using this template with Vuetify. I just cloned this template and added Vuetify, as described [here]( https://vuetifyjs.com/en/getting-started/installation/#existing-projects).

At that point if you just try a trivial change to App.vue you can experience this firsthand. I added a single Vuetify image:

```
<template>
  <v-app>
    <v-img :width="60" src="/vue.svg"></v-img>
    <div>
      <a href="https://vitejs.dev" target="_blank">
        <img src="/logomark_white.png" class="logo" alt="Vite logo" />
      </a>
      <a href="https://vuejs.org/" target="_blank">
        <img src="/vue.svg" class="logo vue" alt="Vue logo" />
      </a>
    </div>
    <HelloWorld msg="Vite + Vue" />
  </v-app>
</template>
```

So this code is in the same file, using the same image, as the code that works. The above will work with an `npm run dev` but if you build it with `npm run build` the resulting binary won't draw the Vuetify image.

Thanks to running into something similar in the past, I tried changing the file path from `/vue.svg` to `./vue.svg` and it works as expected.

Maybe this will help someone else who happens upon this thread.

**Comment by Deluze** [comment] 2024-04-21 14:10
To add some more information to this thread, it's difficult to use the `public` directory on dynamically resolved paths (or the lack thereof).

There's a big difference when it comes to fetching resources from your dev server, compared to the final build.

**Dev Server**
The Vite server will be able to intercept the request to `/image.png`, and respond with the contents of `<project>/public/image.png`. This works as intended.

**Building your app**
During build time, Vite will transform a snippet like
```html
<img src="/image.png">
```
into
```html
<img src="/absolute/path/to/image.png">
```

This is because there is of course no web server running on the host's machine. Instead, all resources need to be loaded directly from the filesystem.

**Runtime computed filepaths**
There's a big caveat when it comes to src paths being computed on run-time.

Imagine the following snippet:

```html
<script setup>
const filename = new Date().getDay() & 1 ? 'vite.svg' : 'vue.svg';
</script>

<template>
  <img :src=`/${filename}`
</template>
```

Vite will not transform `/${filename}` into the absolute path during build time.
The file URL will be something like: `file:///vite.svg` instead.

I'm not sure if there's a Vite option that will always inject the full path when there's a string starting with `/` in certain contexts. Maybe someone else wrote a plugin for that, but I think it is pretty difficult to do, if not impossible to do it correctly.

---

So... are there any other solutions? Yes!

In case you have some icons that you want to show depending on the users device for example:

```html
import androidIconPath from './icons/android.svg';
import appleIconPath from './icons/apple.svg';

<script setup>
const iconPath = 2 > 5 ? androidIconPath : appleIconPath; // silly example
</script>

<template>
  <img :src="iconPath"> <!-- This will work on both dev server and final build! -->
</template>
```

I can believe this can become pretty cumbersome if you have 1000 icons.
In that case, there might be some more fitting options for you: https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url
I think this solution is similar to what @tob-at-lovelace posted.

To conclude, I don't think this is an issue that has something to do with this template specifically.
I think I will leave this issue open to continue discussion and have it open for discoverability.

I don't really maintain this template any more as I'm not using Electron at all at the moment.
If anyone has any suggestions on how to improve the template, suggestions are always welcome :smile:

**Comment by dss886** [comment] 2024-04-30 06:30
Sorry for the late reply to this post. My solution at that time was indeed similar to the ones of @tob-at-lovelace , which using the relative paths. And I did the path-compute job like:

``` typescript
const iconPath = computed(() => {
    if (import.meta.env.DEV) {
        return `/${props.icon}`;
    } else {
        // after packed, we are in renderer/plugins/xxx/
        return `../../${props.icon}`;
    }
});
```

But the solution of @Deluze is new knowledge to me and looks more elegant, I will learn and use it later!

Thanks all, I'm really appreciate about it. @tob-at-lovelace @Deluze

**Comment by Deluze** [comment] 2024-09-29 15:23
Closing this issue as the example used in the template now imports these files instead of using an absolute path (https://github.com/Deluze/electron-vue-template/commit/4c6c937d184c6a9b7de4853f6d581f66e4dcead3) . Hopefully this will reduce confusion for everyone.

**Closed by Deluze** 2024-09-29 15:23 UTC
